
// The code in this file was generated by ChatGPT because i needed help understanding how to map entities, DTOs and how to Update them.

using EducationPlatform.Application.DTOs.Courses;
using EducationPlatform.Domain.Entities;

namespace EducationPlatform.Application.Mappers.Courses;

public static class CourseMapper
{
    // Converts a Entity to a DTO.
    public static CourseResponseDTO ToDTO(CoursesEntity entity) 
        => new CourseResponseDTO
        (
           Id: entity.Id,
           Name: entity.Name,
           Description: entity.Description
        );


    // From DTO to Entity.
    public static CoursesEntity ToEntity(CreateCourseDTO dto)
        => new CoursesEntity
        {
            Name = dto.Name,
            Description = dto.Description,
        };

    // Updates an entity. This code also makes it possible to partially update an entity.
    public static void UpdateEntity(CoursesEntity entity, UpdateCourseDTO dto)
    {
        if (dto.Name is not null)
        {
            entity.Name = dto.Name;
        }

        if (dto.Description is not null)
        {
            entity.Description = dto.Description;
        }

        entity.Concurrency = dto.Concurrency;
    }
}
