
// The code in this file was generated by ChatGPT because i needed help understanding how to map entities, DTOs and how to Update them.

using EducationPlatform.Application.DTOs.Courses;
using EducationPlatform.Domain.Entities;

namespace EducationPlatform.Application.Mappers.Courses;

public static class CourseMapper
{
    // Converts a Entity to a DTO. ( By chatGPT )
    public static CourseResponseDTO ToDTO(CoursesEntity entity) 
        => new CourseResponseDTO // Creates a new DTO with the properties declared in the method. (Only the properties needed for the response).
        (   
           Id: entity.Id,
           Name: entity.Name,
           Description: entity.Description
        );


    // From DTO to Entity.
    public static CoursesEntity ToEntity(CreateCourseDTO dto)
    {
        var course = new CoursesEntity(dto.Name); // The properties that are required and that should be validated are set in the entity.
        course.ValidateDescription(dto.Description); // Optional properties are run through their own validation method if entered from the frontend.

        return course;
    }

    // Updates an entity. This code also makes it possible to partially update an entity.
    public static void UpdateEntity(CoursesEntity entity, UpdateCourseDTO dto)
    {
        if (dto.Name is not null)
        {
            entity.Name = dto.Name;
        }

        if (dto.Description is not null)
        {
            entity.Description = dto.Description;
        }
    }
}
